insert into tb_estado (descricao) values ('Acre');
insert into tb_estado (descricao) values ('Alagoas');
insert into tb_estado (descricao) values ('Amapá');
insert into tb_estado (descricao) values ('Amazonas');
insert into tb_estado (descricao) values ('Bahia');
insert into tb_estado (descricao) values ('Ceará');
insert into tb_estado (descricao) values ('Distrito Federal');
insert into tb_estado (descricao) values ('Espírito Santo');
insert into tb_estado (descricao) values ('Goiás');
insert into tb_estado (descricao) values ('Maranhão');
insert into tb_estado (descricao) values ('Mato Grosso');
insert into tb_estado (descricao) values ('Mato Grosso do Sul');
insert into tb_estado (descricao) values ('Minas Gerais');
insert into tb_estado (descricao) values ('Pará');
insert into tb_estado (descricao) values ('Paraíba');
insert into tb_estado (descricao) values ('Paraná');
insert into tb_estado (descricao) values ('Pernambuco');
insert into tb_estado (descricao) values ('Piauí');
insert into tb_estado (descricao) values ('Rio de Janeiro');
insert into tb_estado (descricao) values ('Rio Grande do Norte');
insert into tb_estado (descricao) values ('Rio Grande do Sul');
insert into tb_estado (descricao) values ('Rondônia');
insert into tb_estado (descricao) values ('Roraima');
insert into tb_estado (descricao) values ('Santa Catarina');
insert into tb_estado (descricao) values ('São Paulo');
insert into tb_estado (descricao) values ('Sergipe');
insert into tb_estado (descricao) values ('Tocantins');
